### ISSUE TITLE
invalid certificate

### ISSUE THREAD

**Issue by SethTisue** [nescalas/northeast-scala-symposium#28]
reported by @deanwampler at https://twitter.com/deanwampler/status/819579810875904002

I also saw this in Safari but was too lazy to open a ticket at the time

**Comment by dwhitney** [comment]
Do we have a cert? At the moment, this is a static site. I don't see any issues unless I use https to access the site. Not sure how to setup a redirect from port 443 to 80 on Heroku and I don't know how to login to the account.

**Comment by softprops** [comment]
I dont beleive we ever had one. I added you as a collaborator on the heroku project @dwhitney
There's an option to configure to configure one here

https://dashboard.heroku.com/apps/nescala/settings

**Comment by dwhitney** [comment]
Well I just tried letsencrypt to get certs for free, but Heroku wants us to
upgrade to a paid account if we're going to use SSL. I don't really want to
do it. Let's just make sure we circulate the "http" address.

D

**Comment by SethTisue** [comment]
I thought Heroku was a sponsor?
